# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=128)),
                ('mal_level', models.IntegerField()),
                ('mal_type', models.CharField(max_length=128)),
                ('mal_info', models.CharField(max_length=128)),
                ('mal_description', models.CharField(max_length=128, null=True)),
                ('is_effect', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=128)),
                ('mal_level', models.IntegerField()),
                ('mal_type', models.CharField(max_length=128)),
                ('mal_info', models.CharField(max_length=128)),
                ('mal_description', models.CharField(max_length=128, null=True)),
                ('is_effect', models.IntegerField(default=1)),
            ],
        ),
    ]
